---
- name: Check if we need to set the control wallet
  ansible.builtin.stat:
    path: "{{ boost_path }}/control_wallet"
  register: control_wallet_file

- name: Set control wallet # lotus-miner actor control set --really-do-it ${PUBLISH_STORAGE_DEALS_WALLET}
  ansible.builtin.shell:
    cmd: "lotus-miner actor control set --really-do-it {{ deals_wallet_address }}"
  environment:
    LOTUS_PATH: "{{ lotus_path }}"
    LOTUS_MINER_PATH: "{{ lotus_miner_path }}"
  register: set_boost_control_wallet
  when: not ( control_wallet_file.stat.exists | default(false) )

- name: If we failed to set the control wallet, fail
  ansible.builtin.assert:
    that:
      - ( set_boost_control_wallet.rc | default(1) ) == 0
  when: not ( control_wallet_file.stat.exists | default(false) )

- name: If we successfully set the control wallet, write the result to a file
  ansible.builtin.copy:
    content: "{{ deals_wallet_address }}"
    dest: "{{ boost_path }}/control_wallet"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: 0600
  when: not ( control_wallet_file.stat.exists | default(false) ) and ( set_boost_control_wallet.rc | default(1) ) == 0