---
# tasks file for fil_booster_http
- name: Get and detect information about the Boost user
  ansible.builtin.user:
    name: "{{ boost_user }}"
    state: present
  check_mode: true
  register: boost_user_details

- name: Initialise Booster Bitswap
  include_tasks: 01-initialise_booster_bitswap.yml

- name: Get peer ID
  include_tasks: 02-get_peer_id.yml

- name: Configure Boostd
  include_tasks: 03-configure_boostd.yml

- name: Install and start Booster Bitswap system service
  include_tasks: 04-install_service.yml
