---
# tasks file for fil_boost
# create_boost_wallets ${INSTALL_DIR}
# set_boost_vars
# send_funds_to_boost
# set_boost_control_wallet
# install_node ${INSTALL_DIR} 
# build_boost ${INSTALL_DIR}

- name: Get and detect information about the Lotus user
  ansible.builtin.user:
    name: "{{ lotus_user }}"
    state: present
  check_mode: true
  register: lotus_user_details

# Prerequisites
- name: Install prerequisites
  include_tasks: 01-install_prerequisites.yml

- name: Create Boost wallets
  include_tasks: 02-create_boost_wallets.yml
  when: not smoketest

- name: Send funds to Boost
  include_tasks: 03-send_funds_to_boost.yml
  when: not smoketest

- name: Set Boost control wallet
  include_tasks: 04-set_boost_control_wallet.yml
  when: not smoketest

- name: Build Boost
  include_tasks: 05-build_boost.yml