---
# tasks file for fil_boost
- name: Create Boost system group
  ansible.builtin.group:
    name: "{{ boost_group }}"
    system: true
    state: present

- name: Create Boost system user
  ansible.builtin.user:
    name: "{{ boost_user }}"
    comment: "Lotus Daemon User"
    shell: /bin/bash
    system: true
    createhome: true
    group: "{{ boost_group }}"
    groups: "sudo,adm"
    append: true

- name: Get and detect information about the Boost user
  ansible.builtin.user:
    name: "{{ boost_user }}"
    state: present
  check_mode: true
  register: boost_user_details

- name: Get and detect information about the Lotus user
  ansible.builtin.user:
    name: "{{ lotus_user }}"
    state: present
  check_mode: true
  register: lotus_user_details

- name: Ensure the Boost directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ boost_user }}"
    group: "{{ boost_group }}"
    mode: '0750'
  with_items:
    - "{{ boost_client_repo }}"
    - "{{ boost_bitswap_repo }}"
    - "{{ boost_path }}"
    - "{{ boost_config_path }}"
    - "{{ boost_log_dir }}"

# Prerequisites
- name: Install prerequisites
  include_tasks: 01-install_prerequisites.yml

- name: Create Boost wallets
  include_tasks: 02-create_boost_wallets.yml
  when: not smoketest

- name: Send funds to Boost
  include_tasks: 03-send_funds_to_boost.yml
  when: not smoketest

- name: Set Boost control wallet
  include_tasks: 04-set_boost_control_wallet.yml
  when: not smoketest

- name: Build Boost
  include_tasks: 05-build_boost.yml

- name: Create YugabyteDB user and database
  include_tasks: 06-create_yugabyte_user.yml

- name: Create configuration and service for boostd-data service
  include_tasks: 07-boostd_data_service.yml

- name: Initialise Boost repository
  include_tasks: 08-initialise_boost_repository.yml

- name: Set limits
  include_tasks: 09-set_limits.yml

- name: Configure Boost LibP2P options
  include_tasks: 10-configure_boost_libp2p.yml