---
# tasks ansible.builtin.file for lotus_worker
- name: Get and detect information about the Lotus user
  ansible.builtin.user:
    name: "{{ lotus_user }}"
    state: present
  check_mode: true
  register: lotus_user_details

- name: Ensure the lotus_worker_path exists
  ansible.builtin.file:
    path: "{{ lotus_worker_path }}-{{ item.name }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: '0750'
  loop: "{{ lotus_workers }}"

- name: Install systemd service for Lotus worker and start Lotus worker
  ansible.builtin.include_tasks: 01-systemd_lotus_worker.yml