---
- name: Gather facts from all hosts
  hosts: all
  gather_facts: true
  become: true

- name: Collect Lotus API info and token
  hosts: lotus_primary
  become: true

  tasks:
    - name: Get lotus info
      ansible.builtin.include_tasks: tasks/get_lotus_info.yml

- name: Collect Lotus Miner API info and token
  hosts: lotus_miner
  become: true

  tasks:
    - name: Get lotus miner info
      ansible.builtin.include_tasks: tasks/get_lotus_miner_info.yml

- name: Debug - Deploy Booster HTTP
  hosts: booster_http
  become: true

  roles:
    - zorlin.fil_booster_http
    - geerlingguy.nginx

- name: Configure Nginx for the stack
  hosts: booster_http
  become: true

  tasks:
    - name: Configure Nginx
      ansible.builtin.include_tasks: tasks/configure_nginx.yml

- name: Configure TLS/SSL using Certbot and Let's Encrypt
  hosts: booster_http
  become: true

  pre_tasks:
    - name: Check that user has changed the default email address
      ansible.builtin.assert:
        that:
          - certbot_email != "hello@filecoin.io"
        fail_msg: "Please update the sp_email setting to your own email address for Certbot registrations."
        success_msg: "Email address {{ certbot_email }} will be used for Certbot."

  roles:
    - role: robertdebock.certbot
      certbot_domains:
        - "{{ sp_domain }}"
      certbot_system: nginx

  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
