---
- name: Gather facts from all hosts
  hosts: all
  gather_facts: true
  become: true

- name: Debug playbook
  hosts: boost
  become: true

  roles:
    #- zorlin.lotus_daemon
    #- zorlin.lotus_miner
    #- zorlin.yugabytedb
    - zorlin.fil_boost
