---
- name: Gather facts from all hosts
  hosts: all
  gather_facts: true
  become: true

- name: Collect Lotus API info and token
  hosts: lotus_primary
  become: true

  tasks:
    - name: Get lotus info
      ansible.builtin.include_tasks: tasks/get_lotus_info.yml

- name: Collect Lotus Miner API info and token
  hosts: lotus_miner
  become: true

  tasks:
    - name: Get lotus miner info
      ansible.builtin.include_tasks: tasks/get_lotus_miner_info.yml

# - name: Debug - Deploy Lotus Worker
#   hosts: lotus_worker
#   become: true

#   roles:
#     - zorlin.fil_lotus

- name: Deploy Lotus
  hosts: boost
  become: true

  roles:
    - zorlin.fil_booster_http