---
- name: Deploy Lotus
  hosts: lotus_primary
  become: true

  roles:
    - zorlin.lotus_daemon

- name: Deploy Lotus Miner
  hosts: lotus_miner
  become: true

  roles:
    - zorlin.lotus_miner

- name: Deploy Boost
  hosts: boost
  become: true

  roles:
    - zorlin.fil_boost

- name: Collect Boost information necessary for next stages
  hosts: boost
  become: true

  tasks:
    - name: Get boost info
      ansible.builtin.include_tasks: tasks/get_boost_info.yml

- name: Set Lotus actors for Boost
  hosts: lotus_miner
  become: true

  roles:
    - zorlin.lotus_boost_actors