---
# transfer_funds
# wait_for_funds
# initialize_sp ${SECTOR_SIZE}
# configure_miner ${MINER_IP} ${MINER_PORT} ${LOTUS_MINER_PATH}
# start_miner ${LOG_DIR}
# #stop_miner
# #start_miner ${LOG_DIR}
# wait_for_miner ${LOG_DIR}

- name: Create parameter cache directory
  file:
    path: "{{ param_cache }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: '0755'

- name: Create parent cache directory
  file:
    path: "{{ parent_cache }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: '0755'

- name: List existing wallets
  shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet list"
  register: wallet_list
  become_user: "{{ lotus_user }}"
  become: true
  changed_when: false

- name: If the wallet list is empty, set number_of_wallets to zero
  set_fact:
    number_of_wallets: 0
  when: wallet_list.stdout == ""

- name: If the wallet list is not empty, set number_of_wallets to the number of wallets in the list
  set_fact:
    number_of_wallets: "{{ wallet_list.stdout_lines[1:] | select('search', 'FIL') | list | length }}"
  when: wallet_list.stdout != ""

- name: If the owner wallet does not exist yet, create it.
  shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet new bls"
  become_user: "{{ lotus_user }}"
  become: true
  when: number_of_wallets == 0

- name: If the worker wallet does not exist yet, create it.
  shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet new bls"
  become_user: "{{ lotus_user }}"
  become: true
  # This when conditional is a little silly, but it should work consistently. We always want to create this second wallet if we create the first one.
  when: number_of_wallets == 1 or number_of_wallets == 0

- name: List existing wallets again if we created any
  shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet list"
  register: wallet_list
  become_user: "{{ lotus_user }}"
  become: true
  changed_when: false

- name: Set the addresses for the owner and worker wallets
  set_fact:
    owner_wallet_address: "{{ wallet_list.stdout_lines[1].split(' ')[0] }}"
    worker_wallet_address: "{{ wallet_list.stdout_lines[2].split(' ')[0] }}"

- name: Print owner and worker wallet addresses
  debug:
    msg:
      - "Owner wallet address: {{ owner_wallet_address }}"
      - "Worker wallet address: {{ worker_wallet_address }}"
  when: owner_wallet_address is defined and worker_wallet_address is defined

- name: Prompt the user to transfer funds
  include_tasks: 01a-transfer_funds.yml

# Now that we have funds, we can initialise our SP
- name: Check whether we need to initialise our SP
  shell:
    cmd: "export LOTUS_PATH={{ lotus_path }} ; lotus-miner --miner-repo {{ lotus_miner_path }} info"
  register: miner_info
  become_user: "{{ lotus_user }}"
  become: true
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Print the output of the miner info command
  debug:
    msg: "{{ miner_info.stderr_lines }}"
  when: miner_info.stderr_lines is defined
  
# We deliberately only initialize the SP with specific error messages. This is to avoid accidentally initialising the SP when we don't need to.
- name: Empty cache folders for initialisation
  block:
    - name: Scan for files in the cache folders
      find:
        paths: 
          - "{{ param_cache }}"
          - "{{ parent_cache }}"
        file_type: "file"
        patterns: "*"
      register: cache_files_to_delete
      become_user: "{{ lotus_user }}"
      become: "true"
    
    - name: Delete files in the cache folders
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ cache_files_to_delete.files }}"

  when: "miner_info.stderr_lines[0] == 'ERROR: could not get API info for StorageMiner: repo directory does not exist. Make sure your configuration is correct'"

- name: Initialize our SP
  include_tasks: 01b-initialize_sp.yml
  when: "miner_info.stderr_lines[0] == 'ERROR: could not get API info for StorageMiner: repo directory does not exist. Make sure your configuration is correct'"

# Now that we have an SP, we can configure our miner
- name: Install initial miner configuration
  template:
    src: lotus-miner.toml.j2
    dest: "{{ lotus_miner_path }}/config.toml"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: '0644'
    backup: true
  notify:
    - Restart Lotus miner