---
- name: Check balances of wallets
  ansible.builtin.shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet list"
  register: wallet_list
  become_user: "{{ lotus_user }}"
  become: true
  changed_when: false

- name: Assert that wallet list is not empty
  ansible.builtin.assert:
    that:
      - wallet_list.stdout != ""
  changed_when: false

- name: Print entire wallet list
  ansible.builtin.debug:
    msg: "{{ wallet_list.stdout_lines }}"

- name: Get owner wallet balance
  ansible.builtin.set_fact:
    owner_wallet_balance: "{{ wallet_list.stdout_lines | select('search', owner_wallet_address) | first | regex_search('\\b([0-9]+\\.?[0-9]*)\\s+FIL\\b') | regex_replace(' FIL', '') }}"

- name: Get worker wallet balance
  ansible.builtin.set_fact:
    worker_wallet_balance: "{{ wallet_list.stdout_lines | select('search', worker_wallet_address) | first | regex_search('\\b([0-9]+\\.?[0-9]*)\\s+FIL\\b') | regex_replace(' FIL', '')  }}"
