---
- name: Set initialization parameters
  ansible.builtin.set_fact:
    init_flags: "export FIL_PROOFS_PARAMETER_CACHE={{ param_cache }} ; export FIL_PROOFS_PARENT_CACHE={{ parent_cache }} ; export LOTUS_SEALING_AGGREGATECOMMITS=false ; export LOTUS_SEALING_BATCHPRECOMMITS=false"

- name: List existing wallets
  ansible.builtin.shell: "export LOTUS_PATH={{ lotus_path }} ; lotus wallet list"
  register: wallet_list
  become_user: "{{ lotus_user }}"
  become: true
  changed_when: false

- name: If there are not at least two wallets in the list, bail - something is wrong!
  ansible.builtin.set_fact:
    number_of_wallets: 0
  when: wallet_list.stdout_lines[1:] | select('search', 'FIL') | list | length < 2

- name: If both wallets exist, set the addresses for the owner and worker wallets
  ansible.builtin.set_fact:
    owner_wallet_address: "{{ wallet_list.stdout_lines[1].split(' ')[0] }}"
    worker_wallet_address: "{{ wallet_list.stdout_lines[2].split(' ')[0] }}"
  when: number_of_wallets | int >= 2

- name: Install environment file for Lotus miner
  ansible.builtin.template:
    src: lotus-miner.env.j2
    dest: /etc/default/lotus-miner
    owner: root
    group: root
    mode: 0644
    backup: true
  notify:
    - Reload systemd
    - Restart Lotus miner
  become: true

- name: Download proof parameters
  ansible.builtin.shell:
    cmd: "bash -c 'IPFS_GATEWAY=$IPFS_GATEWAY lotus-miner fetch-params 32GiB'"
    executable: /bin/bash
    chdir: "{{ lotus_path }}"
  become_user: "{{ lotus_user }}"
  become: true
  environment:
    LOTUS_PATH: "{{ lotus_path }}"
    FIL_PROOFS_PARAMETER_CACHE: "{{ param_cache }}"
    FIL_PROOFS_PARENT_CACHE: "{{ parent_cache }}"
    IPFS_GATEWAY: "{% if ipfs_gateway is defined %}{{ ipfs_gateway }}/ipfs/{% endif %}"
  async: 86400 # 1 day
  poll: 5
  register: lotus_proof_download_status

- name: Check that the proof download worked correctly
  ansible.builtin.assert:
    that:
      - lotus_proof_download_status.rc == 0
    fail_msg: "The proof download did not appear to work correctly. Please check the logs and try again or contact us if you're having continued issues."
    success_msg: "Proof download was successful, we will now proceed to initialise Lotus Miner."

- name: Initialize Lotus miner
  ansible.builtin.shell:
    cmd: "lotus-miner --miner-repo {{ lotus_miner_path }} init --no-local-storage --owner={{ owner_wallet_address }} --worker={{ worker_wallet_address }} --sector-size={{ sector_size }}"
    executable: /bin/bash
    chdir: "{{ lotus_path }}"
  become_user: "{{ lotus_user }}"
  become: true
  environment:
    LOTUS_PATH: "{{ lotus_path }}"
    FIL_PROOFS_PARAMETER_CACHE: "{{ param_cache }}"
    FIL_PROOFS_PARENT_CACHE: "{{ parent_cache }}"
  async: 86400 # 1 day
  poll: 5
  register: lotus_miner_init_status

- name: Check that the Lotus miner was initialized correctly
  ansible.builtin.assert:
    that:
      - lotus_miner_init_status.rc == 0
    fail_msg: "The Lotus miner did not appear to initialize correctly. Please check the logs and try again or contact us if you're having continued issues."
    success_msg: "Lotus miner initialization was successful, we will now proceed to start the Lotus miner."
