---
- name: Install systemd unit file for Lotus Miner
  template:
    src: lotus-miner.service.j2
    dest: /etc/systemd/system/lotus-miner.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart Lotus miner
  register: lotus_miner_systemd_service

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: lotus_miner_systemd_service.changed

- name: Start Lotus miner
  ansible.builtin.systemd:
    name: lotus-miner
    state: started
    enabled: true
