---
- name: Install systemd unit file for Lotus Miner
  ansible.builtin.template:
    src: lotus-miner.service.j2
    dest: /etc/systemd/system/lotus-miner.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart Lotus miner

- name: If we installed a new version of Lotus, use a handler to restart it
  ansible.builtin.command:
    cmd: /bin/true
  changed_when: true
  check_mode: false
  notify: Restart Lotus miner
  when: new_lotus_version_installed.changed

- name: Ensure Lotus Miner is started
  ansible.builtin.systemd:
    name: lotus-miner
    state: started
    enabled: true
  become: true

# TODO(bug):
# This won't work on Lotus Miners that are not also Lotus Nodes.
# We should probably be adding in LOTUS_API_INFO to the environment here.
- name: Check for Lotus Miner API liveness
  ansible.builtin.shell:
    cmd: "lotus-miner info"
  become_user: "{{ lotus_user }}"
  become: true
  environment:
    LOTUS_MINER_PATH: "{{ lotus_miner_path }}"
    LOTUS_PATH: "{{ lotus_path }}"
  register: lotus_miner_info
  retries: 20
  delay: 3
  until: lotus_miner_info.rc == 0

# TODO(feat): We should more gracefully handle restarting Lotus miner.
- name: Flush handlers
  ansible.builtin.meta: flush_handlers