---
- name: Install systemd unit file for Lotus Miner
  ansible.builtin.template:
    src: lotus-miner.service.j2
    dest: /etc/systemd/system/lotus-miner.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart Lotus miner

- name: If we installed a new version of Lotus, use a handler to restart it
  ansible.builtin.command:
    cmd: /bin/true
  changed_when: true
  check_mode: false
  notify: Restart Lotus miner
  when: new_lotus_version_installed.changed

- name: Ensure Lotus Miner is started
  ansible.builtin.systemd:
    name: lotus-miner
    state: started
    enabled: true
  become: true

- name: Retrieve Lotus auth token
  ansible.builtin.command:
    cmd: "cat {{ lotus_user_details.home }}/.lotus{% if use_calibrationnet %}_calibnet{% endif %}/token"
  register: lotus_auth_token
  changed_when: false
  check_mode: false
  become: true
  become_user: "{{ lotus_user }}"
  delegate_to: "{{ groups['lotus_primary'][0] }}"

- name: Set Lotus auth token
  ansible.builtin.set_fact:
    lotus_auth_token: "{{ hostvars[groups['lotus_primary'][0]]['lotus_auth_token']['stdout'] }}"
  changed_when: false
  check_mode: false

- name: Check for Lotus Miner API liveness
  ansible.builtin.shell:
    cmd: "lotus-miner info"
  environment:
    LOTUS_MINER_PATH: "{{ lotus_miner_path }}"
    LOTUS_PATH: "{{ lotus_path }}"
    FULLNODE_API_INFO: "{{ lotus_auth_token }}:/ip4/{{ hostvars[groups['lotus_primary'][0]]['ansible_' + lotusd_bind_interface]['ipv4']['address'] }}/tcp/{{ lotus_daemon_port }}"
  register: lotus_miner_info
  retries: 30
  delay: 5
  until: lotus_miner_info.rc == 0
  become_user: "{{ lotus_user }}"
  become: true
  ignore_errors: true

# TODO(feat): We should more gracefully handle restarting Lotus miner.
- name: Flush handlers
  ansible.builtin.meta: flush_handlers