---
- name: Install systemd unit file for Lotus Miner
  ansible.builtin.template:
    src: lotus-miner.service.j2
    dest: /etc/systemd/system/lotus-miner.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart Lotus miner

- name: If we installed a new version of Lotus, use a handler to restart it
  ansible.builtin.command:
    cmd: /bin/true
  changed_when: true
  check_mode: false
  notify: Restart Lotus miner
  when: new_lotus_version_installed | default(false)

- name: Ensure Lotus Miner is started
  ansible.builtin.systemd:
    name: lotus-miner
    state: started
    enabled: true
  become: true

# TODO(feat): We should more gracefully handle restarting Lotus miner.
- name: Flush handlers
  ansible.builtin.meta: flush_handlers