---
# Ask Lotus Miner to check if we have any storage attached

- name: Get a list of Lotus Miner storage paths
  ansible.builtin.command:
    cmd: "lotus-miner storage list"
  environment:
    LOTUS_MINER_PATH: "{{ lotus_miner_path }}"
  register: lotus_miner_storage_list
  become_user: "{{ lotus_user }}"
  become: true
  changed_when: false
  failed_when: false

- name: Print Lotus miner storage paths
  debug:
    msg: "{{ lotus_miner_storage_list.stdout_lines }}"
  when: lotus_miner_storage_list.stdout_lines is defined and lotus_miner_storage_list.stdout_lines | length > 0

- name: Convert output of Lotus Miner storage paths into a list of UUIDs
  set_fact:
    lotus_miner_storage_uuids: "{{ storage_list|default([]) + [item.split(':')[0]] }}"
    lotus_miner_has_storage: true
  loop: "{{ lotus_miner_storage_list.stdout_lines }}"
  when:
    - "':' in item"
    - item.split(':')[0] is regex('^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')
  failed_when: false