---
# tasks ansible.builtin.file for lotus_miner
- name: Get and detect information about the Lotus user
  ansible.builtin.user:
    name: "{{ lotus_user }}"
    state: present
  check_mode: true
  register: lotus_user_details

- name: Ensure the lotus_miner_path exists
  ansible.builtin.file:
    path: "{{ lotus_miner_path }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: '0750'

- name: Initialize Lotus miner
  ansible.builtin.include_tasks: 01-initialize_lotus_miner.yml

- name: Install systemd service for Lotus miner and start Lotus miner
  ansible.builtin.include_tasks: 02-systemd_lotus_miner.yml

- name: Announce Lotus miner
  ansible.builtin.include_tasks: 03-announce_lotus_miner.yml

- name: Add storage
  ansible.builtin.include_tasks: 04-add_storage.yml