---
- name: Get public IPv4 address using ifconfig.me
  ansible.builtin.uri:
    url: https://ifconfig.me
    return_content: yes
    status_code: 200
    validate_certs: false
    http_agent: curl
  register: boost_get_public_ip
  until: boost_get_public_ip.status == 200
  retries: 3
  delay: 3
  check_mode: false
  when: boost_public_ip is not defined

- name: If we now have a public IPv4 address, set it as boost_public_ip for later use
  ansible.builtin.set_fact:
    boost_public_ip: "{{ boost_get_public_ip.content }}"
  when: boost_public_ip is not defined and boost_get_public_ip.status == 200

- name: Fetch Boost peer ID
  ansible.builtin.command:
    cmd: "/usr/local/bin/boostd net id"
  register: boost_get_peer_id
  check_mode: false
  changed_when: false
  when: boost_peer_id is not defined
  become_user: "{{ boost_user }}"

- name: If we now have a Boost peer ID, set it as boost_peer_id for later use
  ansible.builtin.set_fact:
    boost_peer_id: "{{ boost_get_peer_id.stdout }}"
  when: boost_get_peer_id is defined
