galaxy_info:
  author: Filecoin Project
  namespace: zorlin
  description: Set Boost actors for Lotus
  company: Protocol Labs

  license: MIT

  min_ansible_version: "2.12"

  platforms:
  - name: Ubuntu
    versions:
    - focal
    - jammy

  galaxy_tags: []

dependencies: []