---
# defaults file for lotus_daemon
lotus_user: lotus
lotus_group: lotus
create_lotus_system_user: true

# URL of the Lotus git repository
lotus_git_repo: "https://github.com/filecoin-project/lotus.git"

# Check which version of Lotus matches with which version of Boost and Go: https://boost.filecoin.io/getting-started
lotus_version: "v1.23.2"
golang_version: "1.20.4"
boost_version: "v1.7.2"

# Build Lotus for Calibration testnet instead of mainnet: true / false
# if "true", use the Faucet to give your wallets test FIL: https://faucet.calibration.fildev.network/
use_calibrationnet: true

# Download location for chain snapshot
chain_download_dir: "filecoin_snapshots"

# Port for Lotus Daemon to run on
lotus_daemon_port: 1234

# Port for libp2p host to run on
lotus_libp2p_port: 6665

# Build directory for building software. Originally "${INSTALL_DIR}".
build_dir: "{{ lotus_user_details.home }}/src/"

# Location for the Lotus log file(s)
log_dir: "/var/log/lotus"

# Choose location where Lotus backups will be stored
lotus_backup_base_path: "/opt/backup"

# Location for lotus' chain and data repository. The chain is stored under lotus_path. This requires fast storage (SSD or NVMe).
lotus_path: "{{ lotus_user_details.home }}/.lotus{% if use_calibrationnet %}_calibnet{% endif %}"

# Where to store the API token for Lotus.
lotus_api_token_file: "{{ lotus_path }}/api_token"

# If true, skip the automatic reboot we perform if the NVIDIA driver is installed but the driver is not active
lotus_nvidia_skip_reboot: false

# By default we do not attempt to install the NVIDIA GPU drivers. This is to keep compatibility with AMD GPU-equipped systems.
install_nvidia_driver: false

# Minimum amount of FIL for a wallet to be considered funded. This is used to determine if a wallet is ready to be used for mining.
wallet_fund_threshold: 0.1

# Skip wallet creation, chain sync and import and similar tasks. Just test building the software.
smoketest: false

# If you are ready for mainnet, you know what to do here. See the docs if you're not sure!
ready_for_mainnet: false