---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: lotus_stable
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
  - name: lotus_oldstable
    image: docker.io/geerlingguy/docker-ubuntu2004-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
verifier:
  name: ansible
