---
- name: Install systemd environment file
  ansible.builtin.template:
    src: lotus-daemon.env.j2
    dest: /etc/default/lotus-daemon
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: 0644
  notify:
    - Reload systemd
    - Restart Lotus daemon
  become: true

- name: Install systemd unit file
  ansible.builtin.template:
    src: lotus-daemon.service.j2
    dest: /etc/systemd/system/lotus-daemon.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart Lotus daemon
  become: true

- name: If we installed a new version of Lotus, use a handler to restart it
  ansible.builtin.command:
    cmd: /bin/true
  changed_when: true
  notify: Restart Lotus daemon
  when: new_lotus_version_installed.changed

- name: Start Lotus daemon
  ansible.builtin.systemd:
    name: lotus-daemon
    state: started
    enabled: true
  become: true

- name: Wait for Lotus daemon to be reachable
  ansible.builtin.wait_for:
    host: localhost
    port: "{{ lotus_daemon_port }}"
    delay: 5
    timeout: 300
  become: true
  become_user: "{{ lotus_user }}"
