---
- name: Get public IPv4 address using ifconfig.me
  ansible.builtin.command:
    cmd: "curl -4 https://ifconfig.me"
  register: public_ipv4
  until: public_ipv4.rc == 0
  retries: 3
  delay: 3
  when: lotus_public_ip is not defined

- name: If we now have a public IPv4 address, use it
  ansible.builtin.set_fact:
    lotus_public_ip: "{{ public_ipv4.stdout }}"
  when: lotus_public_ip is not defined and public_ipv4.rc == 0

# We use a clever hack here to loop until we succeed. Ref: https://github.com/ansible/ansible/issues/46203#issuecomment-496545220
- name: Check Lotus reachability
  block:
    - name: Wait for API to be available
      ansible.builtin.wait_for:
        host: localhost
        port: "{{ lotus_libp2p_port }}"
        delay: 0
        timeout: 20

    - name: Ask Lotus if it's publicly reachable
      ansible.builtin.shell:
        cmd: "set -o pipefail ; lotus net reachability"
        executable: /bin/bash
      register: libp2p_reachability
      environment:
        LOTUS_PATH: "{{ lotus_path }}"
      changed_when: false
      become_user: "{{ lotus_user }}"
      become: true
      retries: 5  # Number of retries before giving up
      delay: 10  # Delay in seconds between retries
      until: >
        'ERROR' not in libp2p_reachability.stderr and
        'Public' in libp2p_reachability.stdout

    - name: If publicly reachable, report success!
      ansible.builtin.debug:
        msg: "Lotus daemon is visible on the public network via port {{ lotus_libp2p_port }} on {{ lotus_public_ip }}. Continuing..."
      when: libp2p_reachability.stdout != ""

    - name: If not publicly reachable, report failure, then pause and wait for further input from the user.
      ansible.builtin.debug:
        prompt: "Lotus daemon is not visible via port {{ lotus_libp2p_port }} on {{ lotus_public_ip }}. Check your firewall settings."
      when: libp2p_reachability.stdout == "" or libp2p_reachability.rc != 0
  rescue:
    - name: Pause and wait for further input from the user.
      ansible.builtin.pause:
        prompt: "Lotus daemon is not visible via port {{ lotus_libp2p_port }} on {{ lotus_public_ip }}. Check your firewall and router settings, and restart Lotus. Press [ENTER] to retry"
    - name: Loop back to the start of this task list
      ansible.builtin.include_tasks: 04-check_lotus_reachability.yml