---
# tasks file for lotus_daemon
- name: Create log folder
  ansible.builtin.file:
    path: "{{ log_dir }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: 0700

- name: Get and detect information about the Lotus user
  user:
    name: "{{ lotus_user }}"
    state: present
  check_mode: true
  register: lotus_user_details

- name: Ensure Lotus path is in the Lotus user's ~/.profile file
  ansible.builtin.lineinfile:
    path: "/home/{{ lotus_user }}/.profile"
    line: "export LOTUS_PATH={{ lotus_path }}"
    state: present
    create: true
    owner: "{{ lotus_user }}"
    group: "{{ lotus_group }}"
    mode: 0640

- name: Download chain snapshots
  ansible.builtin.include_tasks: 04-import_chain_snapshot.yml
  when: not smoketest

- name: Install systemd service and environment for Lotus and start Lotus
  ansible.builtin.include_tasks: 05-systemd_lotusd.yml

- name: Synchronize and initialize Lotus
  ansible.builtin.include_tasks: 06-initialize_lotus.yml

- name: Check Lotus reachability
  ansible.builtin.include_tasks: 07-check_lotus_reachability.yml

- name: Check that Lotus is synced
  ansible.builtin.include_tasks: 08-check_lotus_synced.yml
  when: not smoketest

- name: Check that Lotus is installed and appears to be working
  ansible.builtin.include_tasks: 09-final_preflight.yml
