---
# defaults file for fil_booster_bitswap
boost_user: "boost"
boost_group: "boost"

# Locations for Boost directories
boost_client_repo: "{{ boost_user_details.home }}/.boost_client"
booster_bitswap_repo: "{{ boost_user_details.home }}/.boost_bitswap"
boost_path: "{{ boost_user_details.home }}/.boost"
boost_config_path: "/etc/boost"
boost_log_dir: "/var/log/boost"

# Location for lotus miner's data repository.
lotus_miner_path: "{{ lotus_user_details.home }}/.lotusminer{% if use_calibrationnet %}_calibnet{% endif %}"

# Location for lotus' chain and data repository. The chain is stored under lotus_path. This requires fast storage (SSD or NVMe).
lotus_path: "{{ lotus_user_details.home }}/.lotus{% if use_calibrationnet %}_calibnet{% endif %}"

# Build directory for building software.
boost_build_dir: "{{ boost_user_details.home }}/src/"