---
- name: Get CPU flags from /proc/cpuinfo
  ansible.builtin.shell:
    cmd: "cat /proc/cpuinfo | grep 'flags' | head -1 | awk '{print substr($0, index($0, $3))}'"
  register: cpu_flags
  check_mode: false
  changed_when: false

- name: Check for SSE4.2 instruction set before proceeding
  ansible.builtin.assert:
    that:
      - "'sse4_2' in cpu_flags.stdout"  # Checking for SSE4.2 support
    fail_msg: "Your CPU does not support the SSE4.2 instruction set, which is required for YugabyteDB to run. Please use a different CPU."
    success_msg: "Your CPU supports the SSE4.2 instruction set, which is required for YugabyteDB to run. Proceeding with installation."

# We need `acl` for become_user to work correctly.
- name: Install prerequisites
  ansible.builtin.package:
    name: acl
    state: present

- name: Ensure yugabyte group exists
  ansible.builtin.group:
    name: "{{ yugabyte_group }}"
    system: true
    state: present

- name: Ensure Yugabyte user exists
  ansible.builtin.user:
    name: "{{ yugabyte_user }}"
    comment: "Yugabyte Daemon User"
    shell: /bin/bash
    system: true
    createhome: true
    group: "{{ yugabyte_group }}"
    groups: "adm"
    append: true