---
# tasks file for yugabyteDB

- name: Install prerequisites
  ansible.builtin.include_tasks: 01-install_prerequisites.yml

- name: Install binaries
  ansible.builtin.include_tasks: 02-install_binaries.yml

- name: Ensure directories exist
  ansible.builtin.include_tasks: 03-create_directories.yml

- name: Configure and start master
  ansible.builtin.include_tasks: 04-master.yml

- name: Configure and start tserver
  ansible.builtin.include_tasks: 05-tserver.yml
