---
# handlers file for fil_booster_http
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart booster-http
  ansible.builtin.systemd:
    name: booster-http
    state: restarted
    daemon_reload: true