---
# handlers file for yugabyteDB
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart YugabyteDB master
  ansible.builtin.service:
    name: yugabytedb-master
    state: restarted

- name: Restart YugabyteDB tserver
  ansible.builtin.service:
    name: yugabytedb-tserver
    state: restarted
