---
# handlers file for lotus_daemon
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart Lotus daemon
  ansible.builtin.systemd:
    name: lotus-daemon
    state: restarted
    enabled: true