---
- name: Install booster-http systemd service
  ansible.builtin.template:
    src: booster-http.service.j2
    dest: /etc/systemd/system/booster-http.service
    owner: root
    group: root
    mode: '0644'

- name: If we installed a new version of Boost, use a handler to restart booster-http
  ansible.builtin.command:
    cmd: /bin/true
  changed_when: true
  notify: Restart booster-http
  when: install_boost.changed

- name: Start and enable booster-http
  ansible.builtin.systemd:
    name: booster-http
    state: started
    enabled: true
    daemon_reload: true
  notify:
    - Restart booster-http