---
# tasks file for fil_booster_http
- name: Create Boost system group
  ansible.builtin.group:
    name: "{{ boost_group }}"
    system: true
    state: present

- name: Create Boost system user
  ansible.builtin.user:
    name: "{{ boost_user }}"
    comment: "Boost Daemon User"
    shell: /bin/bash
    system: true
    createhome: true
    group: "{{ boost_group }}"
    groups: "sudo,adm"
    append: true

- name: Get and detect information about the Boost user
  ansible.builtin.user:
    name: "{{ boost_user }}"
    state: present
  check_mode: true
  register: boost_user_details

- name: Ensure the Boost directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ boost_user }}"
    group: "{{ boost_group }}"
    mode: '0750'
  with_items:
    - "{{ boost_client_repo }}"
    - "{{ boost_bitswap_repo }}"
    - "{{ boost_path }}"
    - "{{ boost_config_path }}"
    - "{{ boost_log_dir }}"

- name: Set limits
  include_tasks: 01-set_limits.yml

- name: Configure booster-http
  include_tasks: 02-configure_booster_http.yml

- name: Install booster-http as a systemd service and start it
  include_tasks: 03-systemd_service.yml